INSERT INTO bookmarks (title, url, created_at) VALUES
('Java Programming Language', 'https://www.java.com', CURRENT_TIMESTAMP()),
('Python Programming Language', 'https://www.python.org', CURRENT_TIMESTAMP()),
('JavaScript Programming Language', 'https://www.javascript.com', CURRENT_TIMESTAMP()),
('H2 Database Engine', 'https://www.h2database.com', CURRENT_TIMESTAMP()),
('Spring Framework', 'https://spring.io/projects/spring-framework', CURRENT_TIMESTAMP()),
('Hibernate ORM', 'https://hibernate.org/orm/', CURRENT_TIMESTAMP()),
('Docker Containerization Platform', 'https://www.docker.com', CURRENT_TIMESTAMP()),
('Kubernetes Container Orchestration', 'https://kubernetes.io', CURRENT_TIMESTAMP()),
('PostgreSQL Database', 'https://www.postgresql.org', CURRENT_TIMESTAMP()),
('MySQL Database', 'https://www.mysql.com', CURRENT_TIMESTAMP()),
('Redis In-Memory Data Store', 'https://redis.io', CURRENT_TIMESTAMP()),
('Apache Kafka Distributed Streaming Platform', 'https://kafka.apache.org', CURRENT_TIMESTAMP()),
('Elasticsearch Search Engine', 'https://www.elastic.co/elasticsearch/', CURRENT_TIMESTAMP()),
('Apache Spark Big Data Processing', 'https://spark.apache.org', CURRENT_TIMESTAMP()),
('GraphQL API Query Language', 'https://graphql.org', CURRENT_TIMESTAMP()),
('RESTful Web Services', 'https://restfulapi.net', CURRENT_TIMESTAMP()),
('Microservices Architecture', 'https://microservices.io', CURRENT_TIMESTAMP()),
('Serverless Computing', 'https://aws.amazon.com/serverless/', CURRENT_TIMESTAMP()),
('Machine Learning with TensorFlow', 'https://www.tensorflow.org', CURRENT_TIMESTAMP()),
('Artificial Intelligence with OpenAI', 'https://openai.com', CURRENT_TIMESTAMP()),
('Blockchain Technology', 'https://www.ibm.com/topics/what-is-blockchain', CURRENT_TIMESTAMP()),
('Internet of Things (IoT)', 'https://www.ibm.com/internet-of-things', CURRENT_TIMESTAMP()),
('Cybersecurity Best Practices', 'https://www.cisa.gov/cybersecurity-best-practices', CURRENT_TIMESTAMP()),
('Agile Software Development', 'https://www.agilealliance.org/agile101/', CURRENT_TIMESTAMP()),
('DevOps Practices and Tools', 'https://www.atlassian.com/devops', CURRENT_TIMESTAMP());